blogsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')), # modifique esta linha
    path('posts/', include('posts.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),  # edite esta linha
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), # adicione esta linha
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings

class Post(models.Model):
    title = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()  
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.title} ({self.date})'
    
class Comments(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    def __str__(self):
        return f'"{self.text}" - {self.author.username}'
    
class Category(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,  # Use `null=True` se o autor puder ser opcional
        blank=True  # Permite que o autor não seja obrigatório no formulário de criação
    )
    name = models.CharField(max_length=255)
    description = models.TextField()  
    posts = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django.forms import ModelForm
from .models import Post, Comments


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'poster_url',
        ]
        labels = {
            'title': 'Título',
            'content': "Conteúdo",
            'poster_url': 'URL do Poster',
        }

class CommentsForm(ModelForm):
    class Meta:
        model = Comments
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .temp_data import post_data
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post, Comments, Category
from .forms import PostForm, CommentsForm
from django.views import generic
from django.urls import reverse_lazy

class PostListView(generic.ListView):
    model = Post
    template_name = 'posts/index.html'

class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'
    context_object_name = 'post'

class PostCreateView(generic.CreateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/create.html'
    success_url = reverse_lazy('posts:list')  # Ajuste a URL de sucesso conforme necessário

    def get_success_url(self):
        return reverse_lazy('posts:detail', args=[self.object.id])
    
class PostUpdateView(generic.UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'posts/update.html'
    
    def get_success_url(self):
        return reverse_lazy('posts:detail', args=[self.object.id])

class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'posts/delete.html'
    success_url = reverse_lazy('posts:index')

def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comments(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('posts:detail', args=(post_id, )))
    else:
        form = CommentsForm()
    context = {'form': form, 'post': post}
    return render(request, 'posts/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'posts/category.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'posts/index.html'  # Reutilizando o template de listagem de posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_list'] = self.object.posts.all()  # Acessa os posts relacionados à categoria
        context['category_name'] = self.object.name  # Passa o nome da categoria
        return context

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de Posts</h2>

<section>
    {% for category in object_list %}
    <hr>
    <article>
        <header>
            <h3>{{ category.name }}</h3>
        </header>
        <div class="lista-de-cards">
            {% for post in category.posts.all %}
            <div class="card">
                <a href="{% url 'posts:detail' post.id %}">
                    <img src="{{ post.poster_url }}" alt="Poster do Post {{ post.title }}">
                </a>
                <p>{{ post.title }} ({{ post.date|date:"d/m/Y - H:i" }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}
</section>

{% endblock content %}

posts/templates/posts/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentário Post {{ post.title }} ({{ post.date }})</h2>

<form action="{% url 'posts:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar Comentário</button>
</form>

<p><a href="{% url 'posts:detail' post.id %}">Voltar para a página do post</a></p>
{% endblock content %}

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Post</h2>
<form method="post" action="{% url 'posts:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
        <p>
            Você tem certeza que deseja apagar o post "{{ post.title }} ({{ post.date|date:"d/m/y - H:i"  }})"?
        </p>
    <button type="submit">Apagar
</form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }} {{ post.date }}
{% endblock title %}

{% block content %}
<h2> {{ post.title }} ({{ post.date|date:"d/m/y - H:i" }}) </h2>

<section class="dados-de-filme">
  <img src="{{ post.poster_url }}" alt="Poster do post {{ post.title }}" />
  <ul>
    <li> {{ post.content|safe }} </li>
    <li><a href="{% url 'posts:update' post.id %}">Editar </a></li>
    <li><a href="{% url 'posts:delete' post.id %}">Apagar </a></li>
  </ul>
</section>

<hr>

<section>
  <header>
    <h3>Categorias</h3>
  </header>
  <article>
     <div class="lista-de-cards">
         {% for category in post.category_set.all %}
         <div class="card">
             <a href="{% url 'posts:category_detail' category.id %}">
               <h3>{{ category.name }}</h3>
             </a>
             <p>{{ category.description }}</p>
         </div>
         {% endfor %}
      </div>
  </article>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if post.comments.all %}
            {% for comment in post.comments.all %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>{{ comment.author }}</figcaption>
                    <figcaption>{{ comment.date|date:"H:i - d/m/y" }}</figcaption>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não há nenhum comentário nesse post.</p>
        {% endif %}
    </ul>
    <hr>

    <a href="{% url 'posts:comment' post.pk %}"><button>Comente</button></a>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
    {% if category_name %}
    <h2> Posts em {{ category_name }} </h2> 
    {% else %}
    <h2>Todos os Posts</h2> 
    <section>
      <p>
        Quer postar algo?
        <a href="{% url 'posts:create' %}">Adicionar Novo Post</a>
      </p>
    </section>
    {% endif %}

{% if post_list %}
<section class="lista-de-cards">
  {% for post in post_list %}
  <article class="card">
    <a href="{% url 'posts:detail' post.id %}">
      <img src="{{ post.poster_url }}" alt="Poster do post {{ post.title }}">
    </a>
    <p>{{ post.title }} ({{ post.date|date:"d/m/y - H:i" }})</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum post.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Filme {{ post.title }} ({{ post.date|date:"d/m/y - H:i"}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre nós</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Handpoli</i></h1>
<p>Handebol masculino da Escola Politécnica da USP</p>
{% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | HANDPOLI
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Posts</a></li>
                <li><a href="{% url 'posts:category' %}">Categorias</a></li> <!-- adicionar esta linha -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
          </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>